#!/bin/bash
# This bash script creates a symlink in the users home directory
ln -s ~/.dotfiles/bashrc ~/.bashrc
ln -s ~/.dotfiles/profile ~/.profile
ln -s ~/.dotfiles/ipython/ipython_config.py ~/.ipython/profile_default/ipython_config.py
